# Numpy

## Importando a biblioteca

In [ ]:
import numpy as np

## Instanciado arrays

In [ ]:
lista = [1,2,3]
lista

[1, 2, 3]

In [ ]:
np.array(lista) #array de uma dimensão

array([1, 2, 3])

In [ ]:
matriz = [ [1,1,1], [2,2,2], [3,3,3]] #array de duas dimensões
matriz

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [ ]:
np.array(matriz)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
cubo = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
cubo

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [ ]:
np.array(cubo) #array de três dimensões

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Tipos

In [ ]:
np.array(lista, dtype=float)
np.array(lista, dtype=np.int8)
np.array(lista, dtype=np.uint32)
np.array(lista, dtype=np.int32)
np.array(lista, dtype=np.float64)

[1. 2. 3.]
[1 2 3]
[1 2 3]
[1 2 3]
[1. 2. 3.]


## Funções de criação

In [ ]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Copiando e gerando arrays iguais


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2] # B aponta para as duas primeiras posições de A
print('a =', a, '; b =', b)
b += 1
print('a =', a, '; b =', b) # depois da operação de soma, alterou tanto A quanto B

a = [1 2 3 4 5 6] ; b = [1 2]
a = [2 3 3 4 5 6] ; b = [2 3]


In [ ]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy() # B é uma nova array feita a partir das primeiras posições de A
print('a =', a, '; b =', b)
b += 1
print('a = ', a, 'b = ', b) # depois da operação de soma, somente B se altera

a = [1 2 3 4] ; b = [1 2]
a =  [1 2 3 4] b =  [2 3]


## Arange e Reshape

In [ ]:
x = np.arange(0, 11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = np.arange(35).reshape(5, 7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
x = np.arange(30).reshape(5, 3, 2) # 5 x 3 x 2 = 30
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

## Indexação

In [ ]:
x[0] # indexando 1 dimensão

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
x[0][0] # indexando 2 dimensões

array([0, 1])

In [ ]:
x[0][0][0] # indexando 3 dimensões

0

In [ ]:
x = x.reshape(5, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
x[[1, 0, 4]]

array([[ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a = np.arange(0, 10).reshape(2,5)
print("a:", a)
b = np.arange(11, 16)
print("b:", b)

a: [[0 1 2 3 4]
 [5 6 7 8 9]]
b: [11 12 13 14 15]


## Operações

In [ ]:
a + b

array([[11, 13, 15, 17, 19],
       [16, 18, 20, 22, 24]])

In [ ]:
a - b

array([[-11, -11, -11, -11, -11],
       [ -6,  -6,  -6,  -6,  -6]])

In [ ]:
a * b

array([[  0,  12,  26,  42,  60],
       [ 55,  72,  91, 112, 135]])

In [ ]:
b = np.arange(11, 13)
b

array([11, 12])

In [ ]:
a * b

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [ ]:
print(a)
print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
4.5
[2.5 3.5 4.5 5.5 6.5]
[2. 7.]
